"""Add is_grouped_expense field for grouped expenses feature

Revision ID: 3636dd5158d8
Revises: 4b025858c243
Create Date: 2026-02-16 23:50:53.102316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3636dd5158d8'
down_revision: Union[str, Sequence[str], None] = '4b025858c243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_backup_20251116_221526')
    op.add_column('transactions', sa.Column('is_grouped_expense', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_grouped_expense')
    op.create_table('transactions_backup_20251116_221526',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('link_parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('transaction_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('split_share_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('direction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_partial_refund', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_shared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('split_breakdown', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sub_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reference_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('related_mails', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('paid_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_split', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_flagged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
