"""add email ingestion columns to accounts and transactions

Revision ID: 8f63fd6502d2
Revises: k6l7m8n9o0p1
Create Date: 2026-04-06 07:31:49.052629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f63fd6502d2'
down_revision: Union[str, Sequence[str], None] = 'k6l7m8n9o0p1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('alert_sender', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('alert_last_processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('email_message_id', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('statement_confirmed', sa.Boolean(), nullable=True))
    op.create_index('idx_transactions_email_message_id', 'transactions', ['email_message_id'], unique=False)
    op.create_index('idx_transactions_reference_number', 'transactions', ['reference_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_reference_number', table_name='transactions')
    op.drop_index('idx_transactions_email_message_id', table_name='transactions')
    op.drop_column('transactions', 'statement_confirmed')
    op.drop_column('transactions', 'email_message_id')
    op.drop_column('accounts', 'alert_last_processed_at')
    op.drop_column('accounts', 'alert_sender')
    # ### end Alembic commands ###
