"""Add paid_by field to transactions table

Revision ID: ab264540eef4
Revises: 0d03407f2300
Create Date: 2025-10-05 17:26:06.017236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab264540eef4'
down_revision: Union[str, Sequence[str], None] = '0d03407f2300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('paid_by', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'paid_by')
    # ### end Alembic commands ###
