"""add_recurring_fields_to_transactions

Revision ID: b53818b7f053
Revises: a414ac8f0c18
Create Date: 2026-04-12 21:57:04.082221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b53818b7f053'
down_revision: Union[str, Sequence[str], None] = 'a414ac8f0c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_backup_20260319')
    op.add_column('transactions', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('recurrence_period', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('recurring_key', sa.Text(), nullable=True))
    op.create_index('idx_transactions_is_recurring', 'transactions', ['is_recurring'], unique=False)
    op.create_index('idx_transactions_recurring_key', 'transactions', ['recurring_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_recurring_key', table_name='transactions')
    op.drop_index('idx_transactions_is_recurring', table_name='transactions')
    op.drop_column('transactions', 'recurring_key')
    op.drop_column('transactions', 'recurrence_period')
    op.drop_column('transactions', 'is_recurring')
    op.create_table('transactions_backup_20260319',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('transaction_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('split_share_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('direction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_shared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('split_breakdown', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sub_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reference_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('related_mails', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('paid_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_split', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_flagged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_grouped_expense', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('transaction_source', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
