"""add_recurring_fields_to_transactions

Revision ID: b53818b7f053
Revises: a414ac8f0c18
Create Date: 2026-04-12 21:57:04.082221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b53818b7f053'
down_revision: Union[str, Sequence[str], None] = 'a414ac8f0c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('recurrence_period', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('recurring_key', sa.Text(), nullable=True))
    op.create_index('idx_transactions_is_recurring', 'transactions', ['is_recurring'], unique=False)
    op.create_index('idx_transactions_recurring_key', 'transactions', ['recurring_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_recurring_key', table_name='transactions')
    op.drop_index('idx_transactions_is_recurring', table_name='transactions')
    op.drop_column('transactions', 'recurring_key')
    op.drop_column('transactions', 'recurrence_period')
    op.drop_column('transactions', 'is_recurring')
    # ### end Alembic commands ###
