"""add_budgets_tables

Revision ID: fb1fb64e5a93
Revises: b53818b7f053
Create Date: 2026-04-12 22:11:34.071159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1fb64e5a93'
down_revision: Union[str, Sequence[str], None] = 'b53818b7f053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', name='uq_budgets_category_id')
    )
    op.create_index('idx_budgets_category_id', 'budgets', ['category_id'], unique=False)
    op.create_table('budget_overrides',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('budget_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'period', name='uq_budget_overrides_budget_period')
    )
    op.create_index('idx_budget_overrides_budget_id', 'budget_overrides', ['budget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_budget_overrides_budget_id', table_name='budget_overrides')
    op.drop_table('budget_overrides')
    op.drop_index('idx_budgets_category_id', table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
